TEAM-JJINS/cs-algo

- .gitignore
- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- package-lock.json
- package.json
- commit 메시지의 의도 명확성 향상을 위한 Convetional Commit 도입 필요성 대두
- Git Husky 설정
| 실패 케이스 | 성공 케이스 |
|---|---|
| <img width="504" alt="image" src="https://github.com/user-attachments/assets/338f2935-ecc1-46ea-9f87-1417c9f20da9" /> | <img width="528" alt="image" src="https://github.com/user-attachments/assets/5b026c4b-2913-4a8a-8ebf-e009a8145e7a" /> |
> [Chore] Conventional Commit 설정 close #2

- src/main/java/kr/co/csalgo/domain/common/entity/AuditableEntity.java
- src/main/java/kr/co/csalgo/domain/common/entity/IdentifiableEntity.java
- src/main/java/kr/co/csalgo/domain/question/entity/Question.java
- src/main/java/kr/co/csalgo/domain/question/entity/QuestionResponse.java
- src/main/java/kr/co/csalgo/domain/question/entity/QuestionSendingHistory.java
- src/main/java/kr/co/csalgo/domain/question/entity/ResponseFeedback.java
- src/main/java/kr/co/csalgo/domain/user/entity/User.java
- 추후 비즈니스 로직 구현을 위한 데이터베이스 Entity 객체 일괄 생성 필요성 대두
- BaseEntity 구현: 다수의 Entity 객체에서 활용하기 위한 추상 클래스
- `AuditableEntity`: 공통 시간 필드를 선언하는 클래스 
- `IdentifiableEntity`: id 필드를 선언하는 클래스
- 주요 도메인에 대한 Entity 클래스
* User: 사용자 정보
* Question: 문제 정보
* QuestionSendingHistory: 문제 전송 내역
* QuestionResponse: 사용자의 문제 응답
* ResponseFeedback: 사용자의 문제 응답에 대한 피드백 내용
- 없음
> [Feature] entity 생성 close #3

- src/main/resources/application.yml
- resolve #31 
- `spring-boot-devtools` 의존성을 `developmentOnly`로 추가하여 production 환경에서는 로드되지 않도록 설정
- `.java`, `.html`, `.yml` 파일 변경 시 자동으로 애플리케이션이 재시작되도록 설정
- LiveReload 기능 활성화를 위한 설정(`application.yml`) 추가
- `application.yml`에 필요 시 exclude 경로를 지정하여 특정 경로(빌드 결과물 등) 제외
1. 상단 메뉴 → `Run` → `Edit Configurations...` 클릭  
2. 좌측에서 실행 중인 `Application` 항목 선택
3. 우측 상단 `Modify options` 클릭 → `On 'Update' action` 항목 체크
4. `On 'Update' action` 항목을 `Update resources`로 변경  
- → 화면을 나가거나 포커스를 잃을 때 서버가 자동으로 리소스를 반영합니다
1. 상단 메뉴 → `File` → `Settings` (단축키: `Ctrl + Alt + S`)
2. `Build, Execution, Deployment` → `Compiler` 이동
- ✅ `Build project automatically` 체크
1. 상단 메뉴 → `Help` → `Find Action...` (단축키: `Ctrl + Shift + A`)
2. "Registry" 검색 → 클릭
3. `compiler.automake.allow.when.app.running` 항목 체크박스 활성화 (✅)
> 위 …
> [Chore] Spring Devtools를 활용한 개발환경 LiveReload 설정 적용

- .husky/post-checkout
- resolve #33 
- `.env` 파일에서 `GITHUB_PAT` 환경 변수를 읽어오는 로직 추가
- 로컬에서 `In Progress` 상태를 테스트하기가 까다로워 실패하는 스크립트를 작성했었네요...
- `In Review`의 경우에는 이전 PR에서 검증하여서 별도 수정 사항 없습니다.
- 정상 동작 확인 했습니다.
> [Chore] 브랜치 생성 시 in-progress 상태 변경 스크립트 수정 close #33

- src/main/java/kr/co/csalgo/common/exception/CustomBusinessException.java
- src/main/java/kr/co/csalgo/common/exception/ErrorCode.java
- src/main/java/kr/co/csalgo/common/exception/ErrorResponse.java
- src/main/java/kr/co/csalgo/common/exception/GlobalExceptionHandler.java
- src/main/java/kr/co/csalgo/domain/user/service/UserService.java
- src/test/java/kr/co/csalgo/common/exception/GlobalExceptionHandlerTest.java
- src/test/java/kr/co/csalgo/domain/user/service/UserServiceTest.java
- src/test/java/kr/co/csalgo/presentation/exception/TestExceptionController.java
- src/test/java/kr/co/csalgo/presentation/subscription/SubscriptionControllerTest.java
- resolve #23 
- GlobalExceptionHandler 구현
- ErroCode 및 ErrorResponse 객체를 정의하여 예외 발생 시 Response Body 획일화
- CustomException 정의
- UserService 및 UserServiceTest에 CustomException 적용
- 없음
> [Feature] 전역 예외 처리

- src/test/java/kr/co/csalgo/presentation/auth/EmailVerificationControllerTest.java
- 테스트 중 실제 메일이 발송되는 문제 발생
- EmailService를 @MockitoBean으로 mock 처리하여 `sendEmail()` 호출 자체를 무력화
- 없음
> [fix] 테스트 실행 시 메일 발송 방지 #30

- .github/workflows/jacoco-pr-comment.yml
- build.gradle
- q
- src/main/java/kr/co/csalgo/common/sentry/SentryConfig.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/test/java/kr/co/csalgo/common/sentry/SentryConfigTest.java
- resolve #43 
- Sentry 플러그인을 주입하고 `application.yml`에 관련 설정 추가
- `logback-spring.xml`에서 Sentry 로그 레벨을 `WARN` 이상으로 설정
- `common.sentry.SentryConfig`에 `beforeSend` 콜백을 설정하여 Sentry 전송 전에 예외 이벤트를 필터링
- 예외가 `CustomBusinessException`인 경우
- 이벤트의 로그 레벨이 `INFO` 이하인 경우
- 환경변수 추가되었습니다!
| Sentry 이슈 (warn이상만) | 메일 알림 |
|--|--|
| ![스크린샷 2025-05-28 180431](https://github.com/user-attachments/assets/0741441c-f0cd-43bc-8556-29fea39f5bfb) | ![스크린샷 2025-05-28 181038](https://github.com/user-attachments/assets/eabd967d-624e-4ace-8c4c-fa5258ea61ce) |
> [Chore] Sentry 설정 #43

- src/main/resources/templates/fragments/common/navbar.html
- resolves #59 
- `data-bs-target` 옵션의 모달명 수정 (subscribeModal -> subscriptionModal)
- 미처 빼놓고 못 바꿨던 부분이 있었네요... 로컬에서 정상 동작 확인했습니다!
> [Fix] 네비게이션 바 구독하기 버튼 미동작 오류 해결 #59

- src/main/java/kr/co/csalgo/application/problem/dto/SendQuestionMailDto.java
- src/main/java/kr/co/csalgo/presentation/question/QuestionController.java
- src/test/java/kr/co/csalgo/presentation/question/QuestionControllerTest.java
- resolves #69 
- **Controller**
- `@RequestParam` → `@RequestBody` 로 변경하여 JSON 본문 매핑
- `PathVariable questionId` 를 DTO에 주입하도록 `request.setQuestionId(questionId)` 추가
- **DTO**
- `SendQuestionMailDto.Request` 에 `questionId` 필드 추가  
- `@NotNull` 어노테이션 제거 (생성자 호출 시 호출됨으로써 반드시 버그 발생함)
- 없음
> [Fix] sendQuestionMail JSON 바인딩 오류 수정 close #69

- .github/workflows/deploy.yml
- resolve #78 
- PR #80 
- aws cli 설치에서 문제가 생겨서 curl → unzip → install 로 변경했습니다.
- 없음
> [Fix] AWS CLI 설치 오류 해결 #78

- .github/workflows/jacoco-pr-comment.yml
- resolves #93 
- mysql-action 제거하고 services.mysql로 교체
- 없음
> [Fix] CI 프로세스 MySQL 오류 해결 #93

- src/main/resources/static/css/style.css
- src/main/resources/templates/index.html
- resolves #95 
- 네비게이션 바 색상 변경
- 구독하기 버튼 색상 변경
> [Fix] 서비스 대표 색 변경 #95

- build.gradle
- src/main/java/kr/co/csalgo/common/util/MailTemplate.java
- resolves #100 
- 메일 템플릿 내 서비스 주소 `http://` -> `https://`로 수정
- 메일 템플릿 내 svg 파일을 s3 이미지 파일 url로 수정 (9988ef9)
> [Fix] 메일 내 이미지 표시 에러 해결 #100

- src/main/java/kr/co/csalgo/common/util/MailTemplate.java
- resolves #102
- a 태그의 href 속성에 정적 배포 링크(AWS S3) 적용 (7d9cb48)
- 없음
> [Feature] 문제 메일 템플릿에 이용방법 페이지 링크 적용 #102

- src/main/resources/templates/fragments/common/navbar.html
- resolve #113 
- navbar에 이용방법 메뉴 추가
- S3로 호스팅한 FAQ 페이지 링크 연결
- 새탭으로 열리게 함
| navbar | faq 페이지 |
|--|--|
| ![스크린샷 2025-07-08 211406](https://github.com/user-attachments/assets/c4117398-ef99-4824-9802-a0a6123a99a7) | ![스크린샷 2025-07-08 211415](https://github.com/user-attachments/assets/06fb0547-d3b2-4c88-b912-87fb5e0165c2) |
> [Feature] navbar에 ‘이용방법’ 메뉴 추가 및 연결 #113

- csalgo-application/src/main/java/kr/co/csalgo/application/user/dto/UserDto.java
- csalgo-application/src/main/java/kr/co/csalgo/application/user/usecase/GetUserUseCase.java
- csalgo-application/src/test/java/kr/co/csalgo/application/user/usecase/GetUserUseCaseTest.java
- csalgo-domain/src/main/java/kr/co/csalgo/domain/user/repository/UserRepository.java
- csalgo-domain/src/main/java/kr/co/csalgo/domain/user/service/UserService.java
- csalgo-domain/src/test/java/kr/co/csalgo/domain/service/UserServiceTest.java
- csalgo-server/src/main/java/kr/co/csalgo/server/user/UserController.java
- csalgo-server/src/test/java/kr/co/csalgo/server/user/UserControllerTest.java
- resolve #143 
- GET `/api/users` 사용자 목록 조회 API 구현
- page, size 파라미터로 페이징 적용
- default 1페이지 size=10
> [Feature] 회원 목록 조회 API 구현 #143

- csalgo-iac/main.tf
- csalgo-iac/modules/redis/main.tf
- csalgo-iac/modules/redis/outputs.tf
- #162 
- redis 모듈 정의 (aws로 롤백할 경우, 추후 provider 디렉토리 분리하여 관리할 계획)
- redis 모듈 적용
> [Feature] 네이버 클라우드(NKS) Redis 서비스 모듈 설정 #162

- csalgo-application/src/main/java/kr/co/csalgo/application/user/usecase/GetUserUseCase.java
- csalgo-application/src/test/java/kr/co/csalgo/application/user/usecase/GetUserUseCaseTest.java
- csalgo-server/src/main/java/kr/co/csalgo/server/user/UserController.java
- csalgo-server/src/test/java/kr/co/csalgo/server/user/UserControllerTest.java
- resolve #144 
- GET /api/users/{userId} API 구현
- 사용자가 없을 때 404
> [Feature] 회원 상세 조회 API 구현 #144

- .github/workflows/push-to-sourcecommit.yml
- #161 
- SourceCommit 활용을 위한 Workflow 작성
> 개발에 필요한 소스코드와 파일들을 안전하게 저장하고 관리할 수 있는 프라이빗 Git 레포지토리입니다.
`SourceCommit`은 Git 기반의 버전 관리 시스템으로, 팀의 소스코드를 안전하게 저장하고 협업할 수 있는 환경을 제공합니다. GitHub, GitLab과 유사하지만, 네이버 클라우드 내부에서 관리되어 보안성과 접근성이 뛰어난 것이 장점입니다.
- `SourceCommit`에 Push 되었을 때를 트리거로 `SourceDeploy` or `SourcePipeline`을 활용하여 CI/CD 파이프라인 구축
> [Chore] NCP SourceCommit 활용을 위한 Workflow 작성 #162

- .github/workflows/deploy-nks-terraform.yml
- .github/workflows/jacoco-pr-comment.yml
- csalgo-iac/main.tf
- csalgo-iac/modules/scheduler/main.tf
- csalgo-iac/modules/scheduler/variables.tf
- csalgo-iac/variables.tf
- #205 
- GitHub Actions CI/CD workflow 수정
- CI workflow 추가
- CD workflow 추가
- `csalgo-iac` 디렉토리에 `scheduler` 모듈 추가 및 호출
- 없음
> [Chore] scheduler 모듈 배포 설정 #205

- csalgo-scheduler/Dockerfile
- #205 
- `scheduler` 모듈의 Dockerfile 작성
- actions 로그를 통해 오류 원인 식별하여 문제 해결하였습니다.
> [Chore] scheduler 모듈 Dockerfile 작성 #205

- .github/workflows/pr-preview.yml
- csalgo-k8s/charts/csalgo-preview/Chart.yaml
- csalgo-k8s/charts/csalgo-preview/templates/deployment.yaml
- csalgo-k8s/charts/csalgo-preview/templates/ingress.yaml
- csalgo-k8s/charts/csalgo-preview/templates/service.yaml
- csalgo-k8s/charts/csalgo-preview/values.yaml
- csalgo-web/src/main/resources/application.yml
- resolve #231
- 요약
- PR마다 독립적인 Preview 환경을 자동 배포할 수 있도록 CI/CD 파이프라인을 개선했습니다.
- 실제 배포 환경과 동일하게 `csalgo-k8s` Helm 차트를 활용해 preview namespace에 배포되며, 리뷰어는 `https://pr-<번호>.csalgo.co.kr` 도메인에서 결과를 확인할 수 있습니다.
- **Ephemeral Namespace**
- `pr-<번호>` 네임스페이스를 생성하여 격리된 환경에서 실행
- `teardown` 단계에서 자동 정리 → 클러스터 리소스 낭비 방지
- **CI/CD Workflow**
- GitHub Actions → Gradle Build → Docker Buildx → NCR Push → Helm Upgrade
- `csalgo-k8s/charts/csalgo-preview` 차트를 통해 배포 자동화
- **Nginx Ingress + Cloudflare DNS**
- Ingress-Nginx Controller가 PR Preview 트래픽 라우팅 담당
- Cloudflare CNAME(`*.csalgo.co.kr`) → NLB External IP → Nginx Ingress → Service → Pod
- TLS 인증은 Cloudflare 관리, Spring Boot는 `forward-headers-strategy` 로 프록시 환경 대응
- **PR Comment 자동화**
- `thollander/actions-comment-pull-request@v2` 사용
- `mode: upsert` 옵션을 …
> [Chore] PR Preview 환경 구축 #231
